INSERT INTO aircraft (name) VALUES 
('Cessna 206 Stationair'),
('Schweizer RSG 300'),
('Bell 206'),
('MD Helicopters MD 500'),
('Airbus Helicopters Eurocopter AS365 Dauphin'),
('MD Helicopters MD Explorer'),
('Boeing AH-64 Apache'),
('Boeing CH-47 Chinook'),
('Mil Mi-26'),
('Flight Design CT'),
('Ikarus C42'),
('Best Off Skyranger'),
('X-Air Hanuman'),
('Airbus A300'),
('Hawker Siddeley HS 121 Trident'),
('Vickers Vanguard'),
('Boeing 377 Stratocruiser'),
('Breguet 763 Deux-Ponts'),
('Lancair Barracuda'),
('Airbus A300-600ST Beluga'),
('Airbus A350 XWB'),
('Airbus A220'),
('Airbus 321'),
('Embraer E175 E-Jet'),
('Bombardier CRJ900'),
('Antonev An-225 Mriya'),
('Antonev An-10'),
('Tupolev Tu-144'),
('Yakovlev Yak-42'),
('Ilyushin Il-86'),
('Airbus A310'),
('Ilyushin Il-96'),
('Piper PA-25 Pawnee'),
('Cessna 152'),
('Cessna 150');