INSERT INTO pilot (name, dob, sex) VALUES
('Emily "Mongo" Smith', '1993/1/3', 'female'),
('Jessica "Chile Dog" Garcia', '1994/2/6', 'female'),
('Ashley "Turkey" Martinez', '1995/3/9', 'female'),
('Sarah "Ketchup" Williams', '1996/4/12', 'female'),
('Hannah "Shredder" Johnson', '1997/5/15', 'female'),
('Samantha "Max" Rodriguez', '1998/6/18', 'female'),
('Taylor "Mule" Jones', '1999/7/21', 'female'),
('Alexis "Preacher" Hernandez', '2000/8/24', 'female'),
('Elizabeth "Lightning" Brown', '2001/1/27', 'female'),
('Madison "Howler" Davis', '1994/9/30', 'female'),
('Megan "Dead Eye" Garza', '1995/10/2', 'female'),
('Kayla "Cheetah" Lopez', '1996/11/5', 'female'),
('Rachel "Garfield" Gonzalez', '1997/12/8', 'female'),
('Lauren "Cap" Perez', '1998/11/11', 'female'),
('Alyssa "Falcon" Flores', '1999/10/14', 'female'),
('Amanda "Zippy" Gonzales', '2000/9/17', 'female'),
('Brianna "One Ear" Ramirez', '1995/8/20', 'female'),
('Jennifer "Ace" Jackson', '1996/7/23', 'female'),
('Victoria "Scum Bag" Moore', '1997/6/26', 'female'),
('Brittany "Hobo" Wilson', '1998/5/29', 'female'),
('Nicole "Larry" Sanchez', '1999/4/1', 'female'),
('Morgan "Sock Hop" Taylor', '1996/3/4', 'female'),
('Stephanie "Broccoli" Miller', '1997/2/7', 'female'),
('Jasmine "Martini" Thomas', '1998/1/10', 'female'),
('Rebecca "Vegas" White', '1997/10/13', 'female'),
('Abigail "Army" Thompson', '1991/9/16', 'female'),
('Olivia "Vendetta" Harris', '1992/8/19', 'female'),
('Courtney "Scorpion" Martin', '1993/7/22', 'female'),
('Amber "Camo" Walker', '1994/6/25', 'female'),
('Alexandra "Sprite" Anderson', '1995/5/28', 'female'),
('Haley "Shasta" Lewis', '1996/4/3', 'female'),
('Katherine "Vermin" Allen', '1997/3/31', 'female'),
('Michael "Squats" Torres', '1993/1/3', 'male'),
('Jacob "Buzzard" Green', '1994/2/6', 'male'),
('Matthew "Duke" Clark', '1995/3/9', 'male'),
('Christopher "Pastor" Gomez', '1996/4/12', 'male'),
('Joshua "Blue Pill" Hill', '1997/5/15', 'male'),
('Nicholas "Nose" King', '1998/6/18', 'male'),
('Andrew "Deli" Wright', '1999/7/21', 'male'),
('Brandon "Gopher" Hall', '2000/8/24', 'male'),
('Austin "Up Chuck" Young', '2001/1/27', 'male'),
('Tyler "Stank" Castillo', '1994/9/30', 'male'),
('Daniel "Pond Scum" Lee', '1995/10/2', 'male'),
('Joseph "Grizzly" Adams', '1996/11/5', 'male'),
('Zachary "Wolf" Trevino', '1997/12/8', 'male'),
('David "Luxor" Scott', '1998/11/11', 'male'),
('John "Domino" Gutierrez', '1999/10/14', 'male'),
('Ryan "Scary" Robinson', '2000/9/17', 'male'),
('James "Pyro" Reyes', '1995/8/20', 'male'),
('Anthony "Brainiac" Vasquez', '1996/7/23', 'male'),
('William "Tiger" Smith', '1997/6/26', 'male'),
('Justin "Baller" Garcia', '1998/5/29', 'male'),
('Jonathan "Rain Man" Martinez', '1999/4/1', 'male'),
('Alexander "Crackler" Williams', '1996/3/4', 'male'),
('Robert "You Tube" Johnson', '1997/2/7', 'male'),
('Kyle "Zone" Rodriguez', '1998/1/10', 'male'),
('Christian "Chem Lab" Jones', '1997/10/13', 'male'),
('Jordan "Crack Head" Hernandez', '1991/9/16', 'male'),
('Samuel "Soda Dad" Brown', '1992/8/19', 'male'),
('Kevin "Slime" Davis', '1993/7/22', 'male'),
('Benjamin "Munchkin" Garza', '1994/6/25', 'male'),
('Dylan "Ropes" Lopez', '1995/5/28', 'male'),
('Thomas "Cowboy" Gonzalez', '1996/4/3', 'male'),
('Jose "Cutlass" Perez', '1997/3/31', 'male');
INSERT INTO aircraft (name) VALUES 
('Cessna 172 Skyhawk'),
('Beechcraft Musketeer'),
('Beechcraft Bonanza'),
('Boeing 787 Dreamliner'),
('Lockheed L-1011 TriStar'),
('Curtiss C-46 Commando'),
('Curtiss T-32 Condor II'),
('Convair 990 Coronado'),
('Beechcraft King Air'),
('Lockheed L-649 Constellation'),
('Vickers Viscount'),
('Fokker F27 Friendship'),
('Fairchild-Dornier 328JET'),
('Yakovlev Yak-40'),
('Lisunov Li-2'),
('Douglas DC-3'),
('Piper PA-46 Malibu'),
('Piper PA-32 Cherokee Six'),
('Pilatus PC-12'),
('SOCATA TBM'),
('PAC P-750 XSTOL'),
('Cessna 210 Centurion'),
('Cessna 182 Skylane'),
('Antonov An-2'),
('8GCBC Scout'),
('Antonov An-38'),
('Aviat Husky'),
('Barrows Bearhawk'),
('Mitsubishi Regional Jet'),
('DHC-8 Dash 8'),
('Xian MA60'),
('Xian MA600'),
('Comac C919'),
('Boeing 737 Next Generation'),
('McDonnell Douglas MD-90'),
('Lockheed JetStar'),
('Learjet 23'),
('HFB 320 Hansa Jet'),
('Embraer Legacy 600'),
('Embraer EMB-505 Phenom 300'),
('Hawker 400'),
('SyberJet SJ30'),
('Cessna Citation Latitude'),
('Dassault Falcon 50'),
('Breguet Br.1150 Atlantic'),
('Stinson Reliant'),
('Adam A500'),
('Eclipse 500'),
('Cessna 350 Corvalis'),
('Grumman American AA-5'),
('Druine D.60 Condor'),
('Bakeng Deuce'),
('Culp Special'),
('Learjet 28'),
('Cirrus SR22'),
('Cessna 400 TTx'),
('Mooney M20 Acclaim'),
('Pipistrel Panthera'),
('Van''s Aircraft RV-10'),
('Robinson R44'),
('Airbus A320-200'),
('Chotia Weedhopper'),
('Beechcraft Baron 58'),
('Beechcraft Travel Air'),
('Cessna 310'),
('Cessna 180 Skywagon'),
('Piper PA-23 Apache'),
('Piper PA-20 Pacer'),
('Piper PA-18 Super Cub'),
('Piper J-3 Cub'),
('Cessna 170'),
('Antonov An-3'),
('Aeronca Champion'),
('Stinson 108'),
('ERCO Ercoupe'),
('Grob GF 200'),
('Grob G180 SPn'),
('IAI 1124 Westwind'),
('Gulfstream G100'),
('Gulfstream G650'),
('Gulfstream IV G450'),
('Gulfstream G550'),
('Gulfstream G280'),
('Cessna Citation Hemisphere'),
('Cessna Citation V Encore'),
('Fairchild PT-19'),
('Fairchild Swearingen Metroliner'),
('Fairchild Hiller FH-227B'),
('Cessna Citation Model 680 Sovereign'),
('Hawker 800'),
('Canadair Bombardier CL-415 Superscooper'),
('VFW-Fokker 614'),
('Grob G 115 Tutor'),
('Technoavia SP-95'),
('Maule M-4'),
('Maule M-7'),
('Maule M-5'),
('Piper J-5 Cub Cruiser'),
('Sukhoi Superjet 100'),
('Sukhoi Su-80'),
('Quest Kodiak'),
('Sukhoi Su-38'),
('Bell 407'),
('Cessna 206 Stationair'),
('Schweizer RSG 300'),
('Bell 206'),
('MD Helicopters MD 500'),
('Airbus Helicopters Eurocopter AS365 Dauphin'),
('MD Helicopters MD Explorer'),
('Boeing AH-64 Apache'),
('Boeing CH-47 Chinook'),
('Mil Mi-26'),
('Flight Design CT'),
('Ikarus C42'),
('Best Off Skyranger'),
('X-Air Hanuman'),
('Airbus A300'),
('Hawker Siddeley HS 121 Trident'),
('Vickers Vanguard'),
('Boeing 377 Stratocruiser'),
('Breguet 763 Deux-Ponts'),
('Lancair Barracuda'),
('Airbus A300-600ST Beluga'),
('Airbus A350 XWB'),
('Airbus A220'),
('Airbus 321'),
('Embraer E175 E-Jet'),
('Bombardier CRJ900'),
('Antonev An-225 Mriya'),
('Antonev An-10'),
('Tupolev Tu-144'),
('Yakovlev Yak-42'),
('Ilyushin Il-86'),
('Airbus A310'),
('Ilyushin Il-96'),
('Piper PA-25 Pawnee'),
('Cessna 152'),
('Cessna 150');
INSERT INTO cert (name) VALUES
('general aviation'),
('composite'),
('homebuilt'),
('fly-by-wire'),
('ultralight'),
('low-wing'),
('monoplane'),
('high-wing'),
('wide-body'),
('agricultural'),
('trainer'),
('aerobatic'),
('turbofan'),
('supersonic');
INSERT INTO craft_on_cert (cert_id, aircraft_id) VALUES
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Lockheed JetStar')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Learjet 23')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'HFB 320 Hansa Jet')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'HFB 320 Hansa Jet')),
((SELECT id FROM cert WHERE name = 'utility rotor'), (SELECT id FROM aircraft WHERE name = 'Bell 407')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Mooney M20 Acclaim')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Pipistrel Panthera')),
((SELECT id FROM cert WHERE name = 'composite'), (SELECT id FROM aircraft WHERE name = 'Pipistrel Panthera')),
((SELECT id FROM cert WHERE name = 'homebuilt'), (SELECT id FROM aircraft WHERE name = 'Van''s Aircraft RV-10')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Robinson R44')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Robinson R44')),
((SELECT id FROM cert WHERE name = 'fly-by-wire'), (SELECT id FROM aircraft WHERE name = 'Airbus A320-200')),
((SELECT id FROM cert WHERE name = 'narrow-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A320-200')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus A320-200')),
((SELECT id FROM cert WHERE name = 'ultralight'), (SELECT id FROM aircraft WHERE name = 'Chotia Weedhopper')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Beechcraft Baron 58')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Beechcraft Baron 58')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Beechcraft Travel Air')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Cessna 310')),
((SELECT id FROM cert WHERE name = 'low-wing'), (SELECT id FROM aircraft WHERE name = 'Cessna 310')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Cessna 310')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 180 Skywagon')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Piper PA-23 Apache')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Piper PA-23 Apache')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Piper PA-23 Apache')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Piper PA-20 Pacer')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Piper PA-20 Pacer')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Piper PA-18 Super Cub')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Ilyushin Il-86')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Ilyushin Il-86')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Ilyushin Il-86')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Airbus A310')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A310')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Airbus A310')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus A310')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Ilyushin Il-96')),
((SELECT id FROM cert WHERE name = 'agricultural'), (SELECT id FROM aircraft WHERE name = 'Piper PA-25 Pawnee')),
((SELECT id FROM cert WHERE name = 'trainer'), (SELECT id FROM aircraft WHERE name = 'Cessna 152')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 152')),
((SELECT id FROM cert WHERE name = 'personal'), (SELECT id FROM aircraft WHERE name = 'Cessna 152')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 150')),
((SELECT id FROM cert WHERE name = 'personal'), (SELECT id FROM aircraft WHERE name = 'Cessna 150')),
((SELECT id FROM cert WHERE name = 'trainer'), (SELECT id FROM aircraft WHERE name = 'Cessna 150')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Grumman American AA-5')),
((SELECT id FROM cert WHERE name = 'trainer'), (SELECT id FROM aircraft WHERE name = 'Druine D.60 Condor')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Druine D.60 Condor')),
((SELECT id FROM cert WHERE name = 'homebuilt'), (SELECT id FROM aircraft WHERE name = 'Bakeng Deuce')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Bakeng Deuce')),
((SELECT id FROM cert WHERE name = 'homebuilt'), (SELECT id FROM aircraft WHERE name = 'Culp Special')),
((SELECT id FROM cert WHERE name = 'aerobatic'), (SELECT id FROM aircraft WHERE name = 'Culp Special')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Learjet 28')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Learjet 28')),
((SELECT id FROM cert WHERE name = 'homebuilt'), (SELECT id FROM aircraft WHERE name = 'Lancair Barracuda')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A300-600ST Beluga')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Airbus A300-600ST Beluga')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A350 XWB')),
((SELECT id FROM cert WHERE name = 'composite'), (SELECT id FROM aircraft WHERE name = 'Airbus A350 XWB')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Airbus A350 XWB')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Airbus A350 XWB')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus A350 XWB')),
((SELECT id FROM cert WHERE name = 'narrow-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A220')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus A220')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Airbus A220')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Airbus A220')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Airbus 321')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Embraer E175 E-Jet')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Embraer E175 E-Jet')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Bombardier CRJ900')),
((SELECT id FROM cert WHERE name = 'turbofan'), (SELECT id FROM aircraft WHERE name = 'Antonev An-225 Mriya')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Antonev An-10')),
((SELECT id FROM cert WHERE name = 'supersonic'), (SELECT id FROM aircraft WHERE name = 'Tupolev Tu-144')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Tupolev Tu-144')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Tupolev Tu-144')),
((SELECT id FROM cert WHERE name = 'turbofan'), (SELECT id FROM aircraft WHERE name = 'Yakovlev Yak-42')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Yakovlev Yak-42')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Yakovlev Yak-42')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Boeing CH-47 Chinook')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Mil Mi-26')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Flight Design CT')),
((SELECT id FROM cert WHERE name = 'ultralight'), (SELECT id FROM aircraft WHERE name = 'Flight Design CT')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Flight Design CT')),
((SELECT id FROM cert WHERE name = 'trainer'), (SELECT id FROM aircraft WHERE name = 'Ikarus C42')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Ikarus C42')),
((SELECT id FROM cert WHERE name = 'personal'), (SELECT id FROM aircraft WHERE name = 'Ikarus C42')),
((SELECT id FROM cert WHERE name = 'ultralight'), (SELECT id FROM aircraft WHERE name = 'Best Off Skyranger')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Best Off Skyranger')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Best Off Skyranger')),
((SELECT id FROM cert WHERE name = 'ultralight'), (SELECT id FROM aircraft WHERE name = 'X-Air Hanuman')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'X-Air Hanuman')),
((SELECT id FROM cert WHERE name = 'personal'), (SELECT id FROM aircraft WHERE name = 'X-Air Hanuman')),
((SELECT id FROM cert WHERE name = 'wide-body'), (SELECT id FROM aircraft WHERE name = 'Airbus A300')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus A300')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Airbus A300')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Airbus A300')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Hawker Siddeley HS 121 Trident')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Vickers Vanguard')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Vickers Vanguard')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Boeing 377 Stratocruiser')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Breguet 763 Deux-Ponts')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Stinson Reliant')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Stinson Reliant')),
((SELECT id FROM cert WHERE name = 'trainer'), (SELECT id FROM aircraft WHERE name = 'Stinson Reliant')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Adam A500')),
((SELECT id FROM cert WHERE name = 'light business'), (SELECT id FROM aircraft WHERE name = 'Eclipse 500')),
((SELECT id FROM cert WHERE name = 'very light jet'), (SELECT id FROM aircraft WHERE name = 'Eclipse 500')),
((SELECT id FROM cert WHERE name = 'composite'), (SELECT id FROM aircraft WHERE name = 'Cessna 350 Corvalis')),
((SELECT id FROM cert WHERE name = 'low-wing'), (SELECT id FROM aircraft WHERE name = 'Cessna 350 Corvalis')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 350 Corvalis')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 206 Stationair')),
((SELECT id FROM cert WHERE name = 'utility rotor'), (SELECT id FROM aircraft WHERE name = 'Schweizer RSG 300')),
((SELECT id FROM cert WHERE name = 'agricultural'), (SELECT id FROM aircraft WHERE name = 'Schweizer RSG 300')),
((SELECT id FROM cert WHERE name = 'utility rotor'), (SELECT id FROM aircraft WHERE name = 'Bell 206')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Bell 206')),
((SELECT id FROM cert WHERE name = 'utility rotor'), (SELECT id FROM aircraft WHERE name = 'MD Helicopters MD 500')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'MD Helicopters MD 500')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Airbus Helicopters Eurocopter AS365 Dauphin')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'MD Helicopters MD Explorer')),
((SELECT id FROM cert WHERE name = 'utility rotor'), (SELECT id FROM aircraft WHERE name = 'MD Helicopters MD Explorer')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Embraer Legacy 600')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Embraer EMB-505 Phenom 300')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Hawker 400')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'SyberJet SJ30')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Cessna Citation Latitude')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Dassault Falcon 50')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Aviat Husky')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Aviat Husky')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Barrows Bearhawk')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Mitsubishi Regional Jet')),
((SELECT id FROM cert WHERE name = 'jet'), (SELECT id FROM aircraft WHERE name = 'Mitsubishi Regional Jet')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'DHC-8 Dash 8')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'DHC-8 Dash 8')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Xian MA60')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Xian MA60')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Xian MA600')),
((SELECT id FROM cert WHERE name = 'low-wing'), (SELECT id FROM aircraft WHERE name = 'PAC P-750 XSTOL')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'PAC P-750 XSTOL')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = 'Cessna 210 Centurion')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = 'Cessna 210 Centurion')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Cessna 182 Skylane')),
((SELECT id FROM cert WHERE name = 'agricultural'), (SELECT id FROM aircraft WHERE name = 'Antonov An-2')),
((SELECT id FROM cert WHERE name = 'high-wing'), (SELECT id FROM aircraft WHERE name = '8GCBC Scout')),
((SELECT id FROM cert WHERE name = 'general aviation'), (SELECT id FROM aircraft WHERE name = '8GCBC Scout')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Antonov An-38')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Antonov An-38')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Antonov An-38')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Lisunov Li-2')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Lisunov Li-2')),
((SELECT id FROM cert WHERE name = 'fixed-wing'), (SELECT id FROM aircraft WHERE name = 'Douglas DC-3')),
((SELECT id FROM cert WHERE name = 'airliner'), (SELECT id FROM aircraft WHERE name = 'Douglas DC-3')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Douglas DC-3')),
((SELECT id FROM cert WHERE name = 'monoplane'), (SELECT id FROM aircraft WHERE name = 'Douglas DC-3')),
((SELECT id FROM cert WHERE name = 'twin-engine'), (SELECT id FROM aircraft WHERE name = 'Douglas DC-3')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Piper PA-46 Malibu')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'Piper PA-32 Cherokee Six')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'Pilatus PC-12')),
((SELECT id FROM cert WHERE name = 'transport'), (SELECT id FROM aircraft WHERE name = 'Pilatus PC-12')),
((SELECT id FROM cert WHERE name = 'turboprop'), (SELECT id FROM aircraft WHERE name = 'SOCATA TBM')),
((SELECT id FROM cert WHERE name = 'light business'), (SELECT id FROM aircraft WHERE name = 'SOCATA TBM')),
((SELECT id FROM cert WHERE name = 'light'), (SELECT id FROM aircraft WHERE name = 'SOCATA TBM'));
INSERT INTO pilot_has_cert (pilot_id, cert_id) VALUES
((SELECT id FROM pilot WHERE name = 'Jose "Cutlass" Perez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Jose "Cutlass" Perez'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Michael "Squats" Torres'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Matthew "Duke" Clark'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Matthew "Duke" Clark'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Christopher "Pastor" Gomez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Joshua "Blue Pill" Hill'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Joshua "Blue Pill" Hill'), (SELECT id FROM cert WHERE name = 'very light jet')),
((SELECT id FROM pilot WHERE name = 'Nicholas "Nose" King'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'fly-by-wire')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Brandon "Gopher" Hall'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'very light jet')),
((SELECT id FROM pilot WHERE name = 'Daniel "Pond Scum" Lee'), (SELECT id FROM cert WHERE name = 'fly-by-wire')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'John "Domino" Gutierrez'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'John "Domino" Gutierrez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Ryan "Scary" Robinson'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'high-wing')),
((SELECT id FROM pilot WHERE name = 'Robert "You Tube" Johnson'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Kyle "Zone" Rodriguez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Jordan "Crack Head" Hernandez'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Samuel "Soda Dad" Brown'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Samuel "Soda Dad" Brown'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Emily "Mongo" Smith'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'high-wing')),
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Alexis "Preacher" Hernandez'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Elizabeth "Lightning" Brown'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Madison "Howler" Davis'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Megan "Dead Eye" Garza'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Kayla "Cheetah" Lopez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Rachel "Garfield" Gonzalez'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'Lauren "Cap" Perez'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Alyssa "Falcon" Flores'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Amanda "Zippy" Gonzales'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Brianna "One Ear" Ramirez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Jennifer "Ace" Jackson'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Victoria "Scum Bag" Moore'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Brittany "Hobo" Wilson'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Nicole "Larry" Sanchez'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Morgan "Sock Hop" Taylor'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Stephanie "Broccoli" Miller'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Jasmine "Martini" Thomas'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Rebecca "Vegas" White'), (SELECT id FROM cert WHERE name = 'high-wing')),
((SELECT id FROM pilot WHERE name = 'Abigail "Army" Thompson'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Olivia "Vendetta" Harris'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Courtney "Scorpion" Martin'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Amber "Camo" Walker'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Alexandra "Sprite" Anderson'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Haley "Shasta" Lewis'), (SELECT id FROM cert WHERE name = 'aerobatic'));