INSERT INTO aircraft (name) VALUES 
('Grumman American AA-5'),
('Druine D.60 Condor'),
('Bakeng Deuce'),
('Culp Special'),
('Learjet 28'),
('Cirrus SR22'),
('Cessna 400 TTx'),
('Mooney M20 Acclaim'),
('Pipistrel Panthera'),
('Van''s Aircraft RV-10'),
('Robinson R44'),
('Airbus A320-200'),
('Chotia Weedhopper'),
('Beechcraft Baron 58'),
('Beechcraft Travel Air'),
('Cessna 310'),
('Cessna 180 Skywagon'),
('Piper PA-23 Apache'),
('Piper PA-20 Pacer'),
('Piper PA-18 Super Cub'),
('Piper J-3 Cub'),
('Cessna 170'),
('Antonov An-3'),
('Aeronca Champion'),
('Stinson 108'),
('ERCO Ercoupe'),
('Grob GF 200'),
('Grob G180 SPn'),
('IAI 1124 Westwind'),
('Gulfstream G100'),
('Gulfstream G650'),
('Gulfstream IV G450'),
('Gulfstream G550'),
('Gulfstream G280'),
('Cessna Citation Hemisphere'),
('Cessna Citation V Encore'),
('Fairchild PT-19'),
('Fairchild Swearingen Metroliner'),
('Fairchild Hiller FH-227B'),
('Cessna Citation Model 680 Sovereign'),
('Hawker 800'),
('Canadair Bombardier CL-415 Superscooper'),
('VFW-Fokker 614'),
('Grob G 115 Tutor'),
('Technoavia SP-95'),
('Maule M-4'),
('Maule M-7'),
('Maule M-5'),
('Piper J-5 Cub Cruiser'),
('Sukhoi Superjet 100'),
('Sukhoi Su-80'),
('Quest Kodiak'),
('Sukhoi Su-38'),
('Bell 407');
