INSERT INTO aircraft (name) VALUES 
('Cessna 172 Skyhawk'),
('Beechcraft Musketeer'),
('Beechcraft Bonanza'),
('Boeing 787 Dreamliner'),
('Lockheed L-1011 TriStar'),
('Curtiss C-46 Commando'),
('Curtiss T-32 Condor II'),
('Convair 990 Coronado'),
('Beechcraft King Air'),
('Lockheed L-649 Constellation'),
('Vickers Viscount'),
('Fokker F27 Friendship'),
('Fairchild-Dornier 328JET'),
('Yakovlev Yak-40'),
('Lisunov Li-2'),
('Douglas DC-3'),
('Piper PA-46 Malibu'),
('Piper PA-32 Cherokee Six'),
('Pilatus PC-12'),
('SOCATA TBM'),
('PAC P-750 XSTOL'),
('Cessna 210 Centurion'),
('Cessna 182 Skylane'),
('Antonov An-2'),
('8GCBC Scout'),
('Antonov An-38'),
('Aviat Husky'),
('Barrows Bearhawk'),
('Mitsubishi Regional Jet'),
('DHC-8 Dash 8'),
('Xian MA60'),
('Xian MA600'),
('Comac C919'),
('Boeing 737 Next Generation'),
('McDonnell Douglas MD-90'),
('Lockheed JetStar'),
('Learjet 23'),
('HFB 320 Hansa Jet'),
('Embraer Legacy 600'),
('Embraer EMB-505 Phenom 300'),
('Hawker 400'),
('SyberJet SJ30'),
('Cessna Citation Latitude'),
('Dassault Falcon 50'),
('Breguet Br.1150 Atlantic'),
('Stinson Reliant'),
('Adam A500'),
('Eclipse 500'),
('Cessna 350 Corvalis');
