INSERT INTO pilot_has_cert (pilot_id, cert_id) VALUES
((SELECT id FROM pilot WHERE name = 'Jose "Cutlass" Perez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Jose "Cutlass" Perez'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Katherine "Vermin" Allen'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Michael "Squats" Torres'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Jacob "Buzzard" Green'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Matthew "Duke" Clark'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Matthew "Duke" Clark'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Christopher "Pastor" Gomez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Joshua "Blue Pill" Hill'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Joshua "Blue Pill" Hill'), (SELECT id FROM cert WHERE name = 'very light jet')),
((SELECT id FROM pilot WHERE name = 'Nicholas "Nose" King'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'fly-by-wire')),
((SELECT id FROM pilot WHERE name = 'Andrew "Deli" Wright'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Brandon "Gopher" Hall'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Austin "Up Chuck" Young'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Tyler "Stank" Castillo'), (SELECT id FROM cert WHERE name = 'very light jet')),
((SELECT id FROM pilot WHERE name = 'Daniel "Pond Scum" Lee'), (SELECT id FROM cert WHERE name = 'fly-by-wire')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Joseph "Grizzly" Adams'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Zachary "Wolf" Trevino'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'David "Luxor" Scott'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'John "Domino" Gutierrez'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'John "Domino" Gutierrez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Ryan "Scary" Robinson'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'James "Pyro" Reyes'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Anthony "Brainiac" Vasquez'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'William "Tiger" Smith'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Justin "Baller" Garcia'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Jonathan "Rain Man" Martinez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Alexander "Crackler" Williams'), (SELECT id FROM cert WHERE name = 'high-wing')),
((SELECT id FROM pilot WHERE name = 'Robert "You Tube" Johnson'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Kyle "Zone" Rodriguez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Christian "Chem Lab" Jones'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Jordan "Crack Head" Hernandez'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Samuel "Soda Dad" Brown'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Samuel "Soda Dad" Brown'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'utility rotor')),
((SELECT id FROM pilot WHERE name = 'Kevin "Slime" Davis'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Benjamin "Munchkin" Garza'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Dylan "Ropes" Lopez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Thomas "Cowboy" Gonzalez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Emily "Mongo" Smith'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'transport')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'ultralight')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Jessica "Chile Dog" Garcia'), (SELECT id FROM cert WHERE name = 'high-wing'));

INSERT INTO pilot_has_cert (pilot_id, cert_id) VALUES
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Ashley "Turkey" Martinez'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Sarah "Ketchup" Williams'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Hannah "Shredder" Johnson'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Samantha "Max" Rodriguez'), (SELECT id FROM cert WHERE name = 'turbofan')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Taylor "Mule" Jones'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Alexis "Preacher" Hernandez'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Elizabeth "Lightning" Brown'), (SELECT id FROM cert WHERE name = 'aerobatic')),
((SELECT id FROM pilot WHERE name = 'Madison "Howler" Davis'), (SELECT id FROM cert WHERE name = 'light business')),
((SELECT id FROM pilot WHERE name = 'Megan "Dead Eye" Garza'), (SELECT id FROM cert WHERE name = 'wide-body')),
((SELECT id FROM pilot WHERE name = 'Kayla "Cheetah" Lopez'), (SELECT id FROM cert WHERE name = 'twin-engine')),
((SELECT id FROM pilot WHERE name = 'Rachel "Garfield" Gonzalez'), (SELECT id FROM cert WHERE name = 'airliner')),
((SELECT id FROM pilot WHERE name = 'Lauren "Cap" Perez'), (SELECT id FROM cert WHERE name = 'supersonic')),
((SELECT id FROM pilot WHERE name = 'Alyssa "Falcon" Flores'), (SELECT id FROM cert WHERE name = 'personal')),
((SELECT id FROM pilot WHERE name = 'Amanda "Zippy" Gonzales'), (SELECT id FROM cert WHERE name = 'agricultural')),
((SELECT id FROM pilot WHERE name = 'Brianna "One Ear" Ramirez'), (SELECT id FROM cert WHERE name = 'homebuilt')),
((SELECT id FROM pilot WHERE name = 'Jennifer "Ace" Jackson'), (SELECT id FROM cert WHERE name = 'composite')),
((SELECT id FROM pilot WHERE name = 'Victoria "Scum Bag" Moore'), (SELECT id FROM cert WHERE name = 'light')),
((SELECT id FROM pilot WHERE name = 'Brittany "Hobo" Wilson'), (SELECT id FROM cert WHERE name = 'trainer')),
((SELECT id FROM pilot WHERE name = 'Nicole "Larry" Sanchez'), (SELECT id FROM cert WHERE name = 'low-wing')),
((SELECT id FROM pilot WHERE name = 'Morgan "Sock Hop" Taylor'), (SELECT id FROM cert WHERE name = 'general aviation')),
((SELECT id FROM pilot WHERE name = 'Stephanie "Broccoli" Miller'), (SELECT id FROM cert WHERE name = 'turboprop')),
((SELECT id FROM pilot WHERE name = 'Jasmine "Martini" Thomas'), (SELECT id FROM cert WHERE name = 'monoplane')),
((SELECT id FROM pilot WHERE name = 'Rebecca "Vegas" White'), (SELECT id FROM cert WHERE name = 'high-wing')),
((SELECT id FROM pilot WHERE name = 'Abigail "Army" Thompson'), (SELECT id FROM cert WHERE name = 'jet')),
((SELECT id FROM pilot WHERE name = 'Olivia "Vendetta" Harris'), (SELECT id FROM cert WHERE name = 'cabin-class')),
((SELECT id FROM pilot WHERE name = 'Courtney "Scorpion" Martin'), (SELECT id FROM cert WHERE name = 'narrow-body')),
((SELECT id FROM pilot WHERE name = 'Amber "Camo" Walker'), (SELECT id FROM cert WHERE name = 'fixed-wing')),
((SELECT id FROM pilot WHERE name = 'Alexandra "Sprite" Anderson'), (SELECT id FROM cert WHERE name = 'search and rescue')),
((SELECT id FROM pilot WHERE name = 'Haley "Shasta" Lewis'), (SELECT id FROM cert WHERE name = 'aerobatic'));
